# Generated by Django 6.0.7 on 2026-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('icao', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
