DEFAULT_EMAIL_PRESET = {
    "delivery_mode": "SMTP",
    "sender_name": "AirAssist Support",
    "sender_email": "support@airassist.eu",
    "reply_to_email": "support@airassist.eu",
    "smtp_host": "smtp.gmail.com",
    "smtp_port": 587,
    "smtp_username": "support@airassist.eu",
    "use_tls": True,
    "subject_template": "Update for {{case_number}}",
    "body_template": (
        "Dear {{passenger_name}},\n\n"
        "This is an update regarding case {{case_number}} for flight {{flight_number}}.\n\n"
        "Kind regards,\n{{organisation_name}}"
    ),
    "footer_text": "This email was generated by AirAssist.",
}

DEFAULT_PDF_PRESET = {
    "layout": "STANDARD",
    "page_size": "A4",
    "include_branding": True,
    "include_disruption_summary": True,
    "include_passenger_contact": True,
    "include_case_timeline": True,
    "exported_fields": [
        "case_number",
        "passenger_name",
        "flight_number",
        "route",
        "delay_minutes",
        "claim_status",
    ],
    "footer_text": "Generated for internal case review.",
}

ALLOWED_EMAIL_PLACEHOLDERS = {
    "case_number",
    "passenger_name",
    "flight_number",
    "organisation_name",
    "departure_airport",
    "arrival_airport",
}

ALLOWED_PDF_FIELDS = {
    "case_number",
    "passenger_name",
    "passenger_email",
    "flight_number",
    "route",
    "departure_date",
    "delay_minutes",
    "claim_status",
    "assigned_colleague",
    "disruption_type",
}

ALLOWED_PDF_PAGE_SIZES = {"A4", "LETTER"}
MAX_TEMPLATE_LENGTH = 2000
