# Generated by Django 6.0.7 on 2026-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INCOMPLETE', 'Incomplete'), ('VALID', 'Valid'), ('REJECTED', 'Rejected')], default='NEW', max_length=50),
        ),
    ]
