# Generated by Django 6.0.7 on 2026-08-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
