# Generated by Django 6.0.7 on 2026-08-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_restore_case_and_add_passenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CasePassenger',
            new_name='Passenger',
        ),
    ]
