# Generated by Django 6.0.7 on 2026-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_case_assigned_colleague'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='incident_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
