# Generated by Django 6.0.7 on 2026-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_case_incident_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='gdpr_consent',
            field=models.BooleanField(default=False),
        ),
    ]
