# Generated by Django 6.0.7 on 2026-08-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_case_reservation_number_alter_case_gdpr_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='incident_description',
        ),
    ]
