# Generated by Django 6.0.7 on 2026-08-04 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_remove_case_incident_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='compensation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('VALID', 'Valid'), ('ASSIGNED', 'Assigned'), ('INVALID', 'Invalid')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BOARDING_PASS', 'Boarding_Pass'), ('PASSPORT', 'Passport')], max_length=30)),
                ('file', models.FileField(upload_to='case_documents/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('flight_number', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=50)),
                ('reservation_number', models.CharField(max_length=20)),
                ('departing_airport', models.CharField(max_length=3)),
                ('destination_airport', models.CharField(max_length=3)),
                ('planned_departure_time', models.TimeField()),
                ('planned_arrival_time', models.TimeField()),
                ('is_problem_flight', models.BooleanField(default=False)),
                ('is_main_flight', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='case.case')),
            ],
        ),
    ]
