# Generated by Django 5.1.1 on 2026-08-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_case_arrival_airport_case_compensation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='compensation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(choices=[('CANCELATION', 'Cancelation'), ('DELAY', 'Delay'), ('DENIED_BOARDING', 'Denied_Boarding')], max_length=20)),
                ('cancellation_type', models.CharField(blank=True, choices=[('MORE_THAN_14_DAYS', 'More_Than_14_Days'), ('LESS_THAN_14_DAYS', 'Less_Than_14_Days'), ('ON_FLIGHT_DAY', 'On_Flight_Day')], max_length=30, null=True)),
                ('delay_type', models.CharField(blank=True, choices=[('LESS_THAN_3_HOURS', 'Less_Than_3_Hours'), ('MORE_THAN_3_HOURS', 'More_Than_3_Hours'), ('CONNECTION_FLIGHT_LOST', 'Connection_Flight_Lost')], max_length=30, null=True)),
                ('denied_boarding_type', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, null=True)),
                ('denied_boarding_reason', models.CharField(blank=True, choices=[('FLIGHT_OVERBOOKED', 'Flight_Overbooked'), ('AGGRESSIVE_BEHAVIOR', 'Aggressive_Behavior'), ('INTOXICATION', 'Intoxication'), ('UNSPECIFIED_REASON', 'Unspecified_Reason')], max_length=30, null=True)),
                ('airline_motive_mentioned', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('I_DONT_KNOW', 'I_Dont_Know')], max_length=15, null=True)),
                ('airline_motive', models.CharField(blank=True, choices=[('TECHNICAL_PROBLEM', 'Technical_Problem'), ('METEOROLOGICAL_CONDITIONS', 'Meteorological_Conditions'), ('STRIKE', 'Strike'), ('AIRPORT_PROBLEMS', 'Airport_Problems'), ('CREW_PROBLEMS', 'Crew_Problems'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disruptions', to='case.case')),
            ],
        ),
    ]
