# Generated by Django 6.0.7 on 2026-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_alter_case_id_alter_casedocument_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='document_type',
            field=models.CharField(choices=[('BOARDING_PASS', 'Boarding_Pass'), ('PASSPORT', 'Passport'), ('CONTRACT', 'Contract')], max_length=30),
        ),
    ]
