# Generated by Django 6.0.7 on 2026-08-13 19:57

import django.db.models.deletion
from django.conf import settings
# Generated by Django 6.0.7 on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_alter_casedocument_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_alter_role_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_comments', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_comments', to='user.user')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='case.case')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
