# Generated by Django 6.0.7 on 2026-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('VALID', 'Valid'), ('ASSIGNED', 'Assigned'), ('INVALID', 'Invalid'), ('IN_REVIEW', 'In_Review'), ('ELIGIBLE', 'Eligible'), ('NON_ELIGIBLE', 'Non_Eligible')], default='NEW', max_length=20),
        ),
    ]
