# Generated by Django 6.0.7 on 2026-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_replace_legacy_case_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In_Review'), ('ELIGIBLE', 'Eligible'), ('NON_ELIGIBLE', 'Non_Eligible'), ('AWAITING_DOCUMENTS', 'Awaiting_Documents')], default='PENDING', max_length=20),
        ),
    ]
