# Generated by Django 6.0.7 on 2026-08-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_case_conversation_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='uploaded_by',
            field=models.CharField(blank=True, choices=[('PASSENGER', 'Passenger'), ('COLLEAGUE', 'Colleague')], max_length=20, null=True),
        ),
    ]
