# Generated by Django 6.0.7 on 2026-08-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_email', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
